# Generated by Django 3.0.8 on 2020-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollno', models.IntegerField()),
                ('grade', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('phonenum', models.IntegerField()),
            ],
        ),
    ]
