# Generated by Django 3.0.8 on 2020-09-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='phonenum',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='fathername',
            new_name='fathersname',
        ),
    ]
